language: csharp
mono: none
os: linux
dist: xenial
dotnet: 2.1.4
script:
- dotnet build -c Release
- dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push ./bin/Release/RA_ParallelPipeline.*.nupkg -k $MYGET_API_KEY -s https://www.myget.org/F/romanageev-ci/api/v2/package
  on:
    tags: true
    condition: $TRAVIS_TAG =~ -release$
env:
  global:
    secure: AAJVYSdgfBBvZRASewbojNxbU1L4LMXHfVQt15cP+ZNM4UWfWYpNLUVnleMN6atTrK1e7WdabgEwqWzjZ8Tu05XzA0+IdEwZxTkJ42sAvFLYDimj4Mu3deAVw+hgzvCXgq1KCuyN8yTH6mSzOZXHtZxLUPYmLlWgUZj1VeGxzccMXCclGNQSvHIxN3T5n0KD3UtKAzmZBt3jyYPFGtKliESeu4phSwFU5PcC/LA/V0YKclWx0pN37au//aezL6/QsJNKO1ZPNpWXocXPzdmq0aFYadC1feTclYYmE/TEbDXhnqWg82dwH6aZiOSiOnNsNPamqETANgEHRHMhn9phFrHTZlBhLU82qCteNY7aU0+2xTtQ5kEqNoKqtypEUwcEiOAs5MYafxgbyo+xpi7Gc7QrfYpho6NQUEltfSdExpF1sXuUzvjUBXhWoA/31y2jkx2NPF7Mp4sexthEBJpIODnY5LvMiv3WE0iRBlWEmVQzyQ8nmxw0lnco1fDMyjnS5KzAI6W9aAhgwGzVvBHrbMz0fsMvbhs3RELKGnfHi2abI/O6fa/j1nyIsd3VCUZxYj9o0l6blwN3lDEdbuF7v42aF2krCiMolqeqjxuEmzrGi14GAdrWOHV8KP884EfHlmv09uj3FZzsSnItkZFAETILfeKDcHUZsHOdgOEi9Kk=
